### ISSUE TITLE
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader

### ISSUE THREAD

**Issue by avalitan** [girtel/Net2Plan#248]
`Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at com.net2plan.internal.SystemUtils.getClasspath(SystemUtils.java:173)
        at com.net2plan.internal.SystemUtils.configureEnvironment(SystemUtils.java:153)
        at com.net2plan.gui.GUINet2Plan.main(GUINet2Plan.java:518)`

`java --version
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10)
OpenJDK 64-Bit Server VM (build 11.0.6+10, mixed mode)`

**Comment by zombie12344321** [comment]
Did you ever figure this issue out?

**Comment by robinchrist** [comment]
I had the same issue. Try with Java 8, anything newer doesn't seem to work.

```
sudo apt install openjdk-8-jre
/usr/lib/jvm/java-8-openjdk-amd64/bin/java -jar Net2Plan.jar
```

For Ubuntu.
